
const actionTypes = { 
    REQUEST_WEATHER_FORECASTS: 'REQUEST_WEATHER_FORECASTS',
    RECEIVE_WEATHER_FORECASTS: 'RECEIVE_WEATHER_FORECASTS',
    INCREMENT_COUNT: 'INCREMENT_COUNT',
    DECREMENT_COUNT: 'DECREMENT_COUNT',

};


export default actionTypes;